[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/auth/*"
  to = "/auth/index.html"
  status = 200

[[redirects]]
  from = "/item/*"
  to = "/item/index.html"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/profile/index.html"
  status = 200
